const categories = [
    "Mythical Creatures",
    "Superhero Powers",
    "Emoji Descriptions",
    "Things That Are Sticky",
    "Famous Duos",
    "Fictional Currencies",
    "Things You Wear on Your Feet",
    "Types of Dances",
    "Unusual Pets",
    "Things That Are Round",
    "Famous Inventors",
    "Things You Find in a Toolbox",
    "Fairy Tale Characters",
    "Things That Are Spicy",
    "Famous Explorers",
    "Things You Do on a Rainy Day",
    "Types of Birds",
    "Things You Find in a Classroom",
    "Famous Painters",
    "Things That Are Soft",
    "Things You Find in a Park",
    "Types of Pasta",
    "Famous Poets",
    "Things That Are Shiny",
    "Things You Find in a Kitchen",
    "Famous Athletes",
    "Things That Are Sour",
    "Things You Find in a Museum",
    "Types of Hats",
    "Famous Composers",
    "Things That Are Fluffy",
    "Things You Find in a Hospital",
    "Famous Chefs",
    "Things That Are Crunchy",
    "Things You Find in a Garden",
    "Types of Breads",
    "Famous Explorers",
    "Things That Are Smooth",
    "Things You Find in a Garage",
    "Famous Scientists",
    "Things That Are Sticky",
    "Things You Find in a Zoo",
    "Types of Soups",
    "Famous Singers",
    "Things That Are Transparent",
    "Things You Find in a Bedroom",
    "Famous Poets",
    "Things That Are Salty",
    "Things You Find in a Library",
    "Types of Trees",
    "Famous Inventors",
    "Things That Are Fuzzy",
    "Things You Find in a Bathroom",
    "Famous Actors",
    "Things That Are Bitter",
    "Things You Find in a Store",
    "Types of Flowers",
    "Famous Artists",
    "Things That Are Rough",
    "Things You Find in an Office",
    "Famous Writers",
    "Things That Are Cold",
    "Things You Find in a Restaurant",
    "Types of Fruits",
    "Famous Photographers",
    "Things That Are Hot",
    "Things You Find in a School",
    "Famous Musicians",
    "Things That Are Sweet",
    "Things You Find in a Grocery Store",
    "Types of Vegetables",
    "Famous Politicians",
    "Things That Are Wet",
    "Things You Find in a Workshop",
    "Famous Dancers",
    "Things That Are Dry",
    "Things You Find in a Gym",
    "Types of Nuts",
    "Famous Inventors",
    "Things That Are Colorful",
    "Things You Find in a Theater",
    "Famous Comedians",
    "Things That Are Dull",
    "Things You Find in a Bank",
    "Types of Grains",
    "Famous Entrepreneurs",
    "Things That Are Fragile",
    "Things You Find in a Studio",
    "Famous Philosophers",
    "Things That Are Hard",
    "Things You Find in a Post Office",
    "Types of Berries",
    "Famous Architects",
    "Things That Are Soft",
    "Things You Find in a Airport",
    "Famous Journalists",
    "Things That Are Elastic",
    "Things You Find in a Bookstore",
    "Types of Spices",
    "Famous Scientists",
    "Things That Are Sticky",
    "Things You Find in a Cafe",
    "Famous Singers",
    "Things That Are Brittle",
    "Things You Find in a Mall",
    "Types of Herbs",
    "Famous Inventors",
    "Things That Are Smooth",
    "Things You Find in a Clinic",
    "Famous Chefs",
    "Things That Are Lumpy",
    "Things You Find in a Market",
    "Types of Cheeses",
    "Famous Dancers",
    "Things That Are Prickly",
    "Things You Find in a Salon",
    "Famous Poets",
    "Things That Are Mushy",
    "Things You Find in a Pharmacy",
    "Types of Beans",
    "Famous Photographers",
    "Things That Are Slimy",
    "Things You Find in a Factory",
    "Famous Athletes",
    "Things That Are Fluffy",
    "Things You Find in a Hotel",
    "Types of Mushrooms",
    "Famous Inventors",
    "Things That Are Bouncy",
    "Things You Find in a Courthouse",
    "Famous Musicians",
    "Things That Are Gooey",
    "Things You Find in a Pharmacy",
    "Types of Peppers",
    "Famous Comedians",
    "Things That Are Fuzzy",
    "Things You Find in a Laboratory",
    "Famous Philosophers",
    "Things That Are Greasy",
    "Things You Find in a Supermarket",
    "Types of Melons",
    "Famous Entrepreneurs",
    "Things That Are Rubbery",
];

const categoriesLength = categories.length;

export function getRandomCategories(number: number): string[] {
    const randomCategories = new Set<string>();
    while (randomCategories.size < number) {
        randomCategories.add(
            categories[Math.floor(Math.random() * categoriesLength)]
        );
    }
    return Array.from(randomCategories);
}
